config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index" # for default route
  resources :posts, only: [:create, :new ]
  resources :users, only: [:index, :show, :new, :create, :destroy] do
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :update_comment_counter

  private

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  after_save :update_user_posts_count
  after_save :recent_five_comments

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_five_comments
    comments.last(5)
  end

  private

  def update_user_posts_count
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :trackable, :lockable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_three_posts
    posts.last(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(
      text: comment_params,
      author_id: current_user.id,
      post_id: @post.id
    )

    @comment.save

    redirect_to user_path(params[:user_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text)[:text]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])

    like = current_user.likes.new(
      author_id: current_user.id,
      post_id: @post.id
    )
    like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.author
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @new_post = current_user.posts.new(post_params)
    @new_post.save

    redirect_to user_path(current_user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text).with_defaults(comments_counter: 0, likes_counter: 0)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    UserMailer.with(user: @user).welcome_email.deliver_later

    format.html { redirect_to(@user, notice: 'User was successfully created.') }
    format.json { render json: @user, status: :created, location: @user }

    # redirect_to users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :photo, :bio, :posts_counter).with_defaults(posts_counter: 0)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>  <%# this loads Sprockets/Rails asset pipeline %>
    <%= javascript_importmap_tags %> <%#  this loads JS from importmaps %>

    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta3/css/bootstrap.min.css" integrity="sha512-N415hCJJdJx+1UBfULt+i+ihvOn42V/kOjOpp1UTh4CZ70Hx5bDlKryWaqEKfY/8EYOu/C2MuyaluJryK1Lb5Q==" crossorigin="anonymous" />
 
  <body>
    <header>
      <%= render partial: "shared/header" %>
    </header>

    <p class="notice"><%= notice%></p>
    <p class="alert"><%= alert%></p>
    
    <%= yield %>
    
    <footer>
      <%= render partial: "shared/footer" %>
    </footer>
  </body>
</html>

app/views/posts/index.html.erb
<% user = User.find(params[:user_id]) %>

<div class="container m-5">
        
    <%= render "shared/user_card", user: user %>
        
    <% posts = Post.where(author_id: user.id) %>
    

    <% posts.each do |post| %>
        <% comments = Comment.where(author_id: user.id , post_id: post.id) %>
        <%= render "shared/post_card", post: post , user: user %> 
        <%= render "shared/comments_list", comments: comments, user: user %> 
    <% end %>

    <a class="btn btn-outline-dark" href="<%= users_path %>">Back</a>
    <a class="btn btn-outline-dark">Pagination</a>
</div>

app/views/posts/new.html.erb
<h1>Add new post</h1>

<%= render 'shared/add_post_form' %>

app/views/posts/show.html.erb
<div class="d-flex flex-column gap-3 m-5">
    <% user = User.find(params[:user_id])  %>
    <% post_id = params[:id] %>

    <% p = Post.where(id: post_id) %>

    <% p.each do |post| %>
        <%= render "shared/post_card", post: post , user: user%> 
    <% end %>

    <%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/likes", scope: :like do |form| %>
        <%= form.submit "Like "%>
    <% end %>

    <div class="d-flex flex-column gap-3 mt-5 mb-5">
        <% comments = Comment.where(author_id: user.id , post_id: post_id) %>
 
        <h4>comments list</h4>        
        <%= render "shared/comments_list", comments: comments, user: user %> 
    </div>
    <div>
        <h4>add comment please </h4>
        <%= render partial: "shared/add_comments", local: { post: @post } %>
    </div>
 
</div>

    
   

app/views/shared/_add_comments.html.erb
<%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/comments", scope: :comment do |form| %>
    <div class="d-flex flex-column" >
        <%= form.text_area :text, placeholder: "Add comment...", rows: 5, required: true %>
        <%= form.submit "Comment" %>
    </div>
<% end %>

app/views/shared/_add_post_form.html.erb
 <%= form_with model: Post do |form| %> 
<div class="container border border-dark m-5 p-3 box-shadow">
    <div>    

        <div class="row">
                <div class="col-3">
                    <%= form.label :title %>                    
                </div>
      
                <div class="col-8">                 
                    <%= form.text_field :title %>
                </div>
        </div>   

        <div class="row">  
                <div class="col-3">
                    <%= form.label :text %>                    
                </div>                

                <div class="col-8">
                    <%= form.text_area :text %>
                </div>
        </div>   

        <div class="row">    
            <div class=col-3>            
                <%= form.submit "Add Post" %>                
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/shared/_add_user_form.html.erb
<%= form_with model: @user do |form| %>
<div class="container border border-dark m-5 p-3 box-shadow">
    <div>    

        <div class="row">
                <div class="col-3">
                    <%= form.label :name %>
                </div>

                <div class="col-8">
                    <%= form.text_field :name %>
                </div>
        </div> 

        <div class="row">
                <div class="col-3">
                    <%= form.label :photo %>                    
                </div>
      
                <div class="col-8">                 
                    <%= form.text_field :photo %>
                </div>
        </div>   

        <div class="row">  
                <div class="col-3">
                    <%= form.label :bio %>                    
                </div>                

                <div class="col-8">
                    <%= form.text_area :bio %>
                </div>
        </div>   

        <div class="row">    
            <div class=col-3>            
                <%= form.submit "Add User" %>                
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/shared/_comments_list.html.erb
<div class="container border border-dark">
    <% comments.each do |comment| %>
        <p><%= user.name %> : <%= comment.text %></p>
    <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer-copyright text-center py-3">© 2022 Copyright:
    <a href="/"> Maen.com</a>
  </div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div >
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"  href="<%= users_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= new_user_path %>">Add User</a>
        </li>
      </ul>
    </div>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
    </div>
  </div>
</nav>

app/views/shared/_post_card.html.erb
            
<% c = Comment.where(author_id: user.id , post_id: post.id) %>
<% l = Like.where(author_id: user.id , post_id: post.id) %>
            
<div class="border border-dark mt-1 mb-1">
    <a href="<%= user_post_path(user.id,post.id) %>"><h4><%= post.title %></h4></a>
    <%= post.text %>
    <h6>Post Author : <%= user.name %></h6>
    <h6>Comments No : <%= c.length %></h6>
    <h6>Likes No : <%= l.length %></h6>
</div>
 

app/views/shared/_user_card.html.erb
<div class="d-flex gap-3">    
    
    <a href="<%= user_path(user) %>" id="profile-img">
    <img src="<%= user.photo %>" alt="user image" class="m2 border border-dark"/> 
    </a>
    
    <div class="d-flex flex-row justify-content-between align-items-center border border-dark w-100 p-2">
        <p class="h4"><%= user.name %></p>
        <div class="d-flex gap-1 align-self-end">
            <p class="small fw-bold">Number of posts:</p>
            <p class="small fw-bold"><%= user.posts_counter %></p>            
        </div>               
 
 
        <div>
            <a class="btn btn-outline-dark mb-1" href="<%= new_post_path %>">Add Post</a>
            <%= button_to "delete", user_path(:id => user.id), :method => :delete, class: "btn btn-outline-dark" %>
        </div>

       
    </div>  

</div>

app/views/users/index.html.erb
<div class="d-flex flex-column gap-3 m-5">

<% User.all.each do |user| %>
    <%= render "shared/user_card", user: user %>   
<% end %>
</div>

app/views/users/new.html.erb
<h1>Add new user</h1>

<%= render 'shared/add_user_form' %>

app/views/users/show.html.erb
<% user = User.find(params[:id]) %>

<div class="container m-5">
        
    <%= render "shared/user_card", user: user %>
        
    <div class="border border-dark mt-3 mb-5">
        <h4>Bio</h4>
        <p class="small"><%= user.bio %></p>
    </div>


    <% p =  user.recent_three_posts %>

         
    <% p.each do |post| %>
        <%= render "shared/post_card", post: post , user: user%> 
    <% end %>


    <a class="btn btn-outline-dark" href="<%= users_path %>">Back</a>
    <a class="btn btn-outline-dark" href="<%= user_posts_path(user) %>">See all posts</a>
</div>   